name: autosync
on:
  schedule:
    - cron: 0 8 * * fri
  workflow_dispatch:
  
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
        
      - name: Resync Code
        run: |
          chmod +x ./autosync.sh
          ./autosync.sh
        
      - name: Commit files
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          status_log=$(git status -sb)
          if [ "$status_log" == "## master...origin/master" ];then
            echo "nothing to commit, working tree clean"
          else
            git add .
            git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
          endif
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
